language: node_js
cache: npm
stages:
  - check
  - test
  - cov

node_js:
  - '12'

os:
  - linux
  - osx
  - windows

script: npx nyc -s npm run test -- --bail
after_success: npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov

notifications:
  email: false
